server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: user-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:53cr37}
      expire-length: ${JWT_EXPIRE_LENGTH:3600000}
cors:
  originPatterns: ${CORS_ORIGIN_PATTERNS:[http://localhost:8080,http://localhost:3000,http://localhost:5173,http://localhost:8082]}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /user-service/v3/api-docs/#swagger-config
    url: /user-service/v3/api-docs
# springdoc:
#   api-docs:
#     path: /v3/api-docs
#   swagger-ui:
#     path: /swagger-ui.html
#     url: /v3/api-docs
