services:
  # Email Service
  email-service:
    build:
      context: .
    container_name: email-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_HOST=${DB_HOST:-mysql-shared}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-email_db}
      - DB_USERNAME=${DB_USERNAME:-email_user}
      - DB_PASSWORD=${DB_PASSWORD:-email_password}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EUREKA_URI=${EUREKA_URI}
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - spring-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:${SERVER_PORT}/actuator/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  spring-network:
    external: true
