services:
  # User Service
  user-service:
    build:
      context: .
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_URI=${EUREKA_URI}
      - SERVER_PORT=${SERVER_PORT}

    networks:
      - spring-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:${SERVER_PORT}/actuator/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  spring-network:
    external: true

volumes:
  mysql-user-data:
